/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-01-07 05:47:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/eclipseSTS/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/103ajax/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/sboard/../include/header.jsp", Long.valueOf(1628642464000L));
    _jspx_dependants.put("/WEB-INF/views/sboard/../include/footer.jsp", Long.valueOf(1628641978000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639964194546L));
    _jspx_dependants.put("jar:file:/C:/eclipseSTS/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/103ajax/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Page Title</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/ex/resources/css/template.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <h1>My Website</h1>\r\n");
      out.write("  <p>A website created by me.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("  <a href=\"#\">Link</a>\r\n");
      out.write("  <a href=\"#\">Link</a>\r\n");
      out.write("  <a href=\"#\">Link</a>\r\n");
      out.write("  <a href=\"#\" class=\"right\">Link</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"side\">\r\n");
      out.write("    <h2>About Me</h2>\r\n");
      out.write("    <h5>Photo of me:</h5>\r\n");
      out.write("    <div class=\"fakeimg\" style=\"height:200px;\">Image</div>\r\n");
      out.write("    <p>Some text about me in culpa qui officia deserunt mollit anim..</p>\r\n");
      out.write("    <h3>More Text</h3>\r\n");
      out.write("    <p>Lorem ipsum dolor sit ame.</p>\r\n");
      out.write("    <div class=\"fakeimg\" style=\"height:60px;\">Image</div><br>\r\n");
      out.write("    <div class=\"fakeimg\" style=\"height:60px;\">Image</div><br>\r\n");
      out.write("    <div class=\"fakeimg\" style=\"height:60px;\">Image</div>\r\n");
      out.write("  </div>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#modDiv {\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 20%;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	margin-top: -50px;\r\n");
      out.write("	margin-left: -150px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	z-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	var bno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	var page=1;\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		\r\n");
      out.write("		$(\"#replies\").on(\"click\",\".replyLi button\",function(){\r\n");
      out.write("			var reply=$(this).parent();\r\n");
      out.write("			var rno=reply.attr(\"data-rno\");\r\n");
      out.write("			var replytext=reply.text();\r\n");
      out.write("			$(\".modal-title\").html(rno);\r\n");
      out.write("			$(\"#replytext\").val(replytext);\r\n");
      out.write("			$(\"#modDiv\").show(\"slow\");\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		//리플작업시작\r\n");
      out.write("		//read페이지는 특정글을 읽을때 들어와서 bno정보를 가지고 있다.\r\n");
      out.write("		//처음 read페이지에 들어 왔을때 page는 1이 된다.\r\n");
      out.write("		//bno page\r\n");
      out.write("	\r\n");
      out.write("		getPageList(page);\r\n");
      out.write("		$(\"#replyModBtn\").on(\"click\",function(){\r\n");
      out.write("			  var rno = $(\".modal-title\").html();\r\n");
      out.write("			  var replytext = $(\"#replytext\").val();\r\n");
      out.write("			  $.ajax({\r\n");
      out.write("					type:'put',\r\n");
      out.write("					url:'/ex/replies/'+rno,\r\n");
      out.write("					headers: { \r\n");
      out.write("					      \"Content-Type\": \"application/json\"},\r\n");
      out.write("					data:JSON.stringify({replytext:replytext}), \r\n");
      out.write("					dataType:'text', \r\n");
      out.write("					success:function(result){\r\n");
      out.write("						console.log(\"result: \" + result);\r\n");
      out.write("						if(result == 'SUCCESS'){\r\n");
      out.write("							alert(\"수정 되었습니다.\");\r\n");
      out.write("							 $(\"#modDiv\").hide(\"slow\");\r\n");
      out.write("							//getAllList();\r\n");
      out.write("							 getPageList(page);\r\n");
      out.write("						}\r\n");
      out.write("				}});\r\n");
      out.write("		});\r\n");
      out.write("		$(\"#closeBtn\").on(\"click\", function() {\r\n");
      out.write("			$(\"#modDiv\").hide(\"slow\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#replyDelBtn\").on(\"click\", function() {\r\n");
      out.write("			var rno = $(\".modal-title\").html();\r\n");
      out.write("			//var replytext = $(\"#replytext\").val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'delete',\r\n");
      out.write("				url : '/ex/replies/' + rno,\r\n");
      out.write("				headers : {\r\n");
      out.write("					\"Content-Type\" : \"application/json\"\r\n");
      out.write("				},\r\n");
      out.write("				dataType : 'text',\r\n");
      out.write("				success : function(result) {\r\n");
      out.write("					console.log(\"result: \" + result);\r\n");
      out.write("					if (result == 'SUCCESS') {\r\n");
      out.write("						alert(\"삭제 되었습니다.\");\r\n");
      out.write("						$(\"#modDiv\").hide(\"slow\");\r\n");
      out.write("						//getAllList();\r\n");
      out.write("						getPageList(page);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\".pagination\").on(\"click\",\"a\",function(event){\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			page=$(this).attr(\"href\");\r\n");
      out.write("			getPageList(page);\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		$(\"#replyAddBtn\").on(\"click\", function() {\r\n");
      out.write("			var replyer = $(\"#newReplyWriter\").val();\r\n");
      out.write("			var replytext = $(\"#newReplyText\").val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'post',\r\n");
      out.write("				url : '/ex/replies',\r\n");
      out.write("				headers : {\r\n");
      out.write("					\"Content-Type\" : \"application/json\"\r\n");
      out.write("				},\r\n");
      out.write("				dataType : 'text',\r\n");
      out.write("				data : JSON.stringify({\r\n");
      out.write("					bno : bno,\r\n");
      out.write("					replyer : replyer,\r\n");
      out.write("					replytext : replytext\r\n");
      out.write("				}),\r\n");
      out.write("				success : function(result) {\r\n");
      out.write("					if (result == 'SUCCESS') {\r\n");
      out.write("						alert(\"등록 되었습니다.\");\r\n");
      out.write("						//getAllList();\r\n");
      out.write("						getPageList(page); \r\n");
      out.write("						//1번페이지를 보여줄 예정\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//리플작업종료\r\n");
      out.write("		var fObject = $(\".form\");\r\n");
      out.write("		\r\n");
      out.write("		$(\".btnList\").on(\"click\", function() {\r\n");
      out.write("\r\n");
      out.write("			fObject.attr(\"method\", \"get\");\r\n");
      out.write("			fObject.attr(\"action\", \"/ex/sboard/list\");\r\n");
      out.write("			fObject.submit();\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("		$(\".btnRemove\").on(\"click\", function() {\r\n");
      out.write("			fObject.attr(\"action\", \"/ex/sboard/remove\");\r\n");
      out.write("			fObject.submit();\r\n");
      out.write("		})\r\n");
      out.write("		$(\".btnModify\").on(\"click\", function() {\r\n");
      out.write("			fObject.attr(\"method\", \"get\");\r\n");
      out.write("			fObject.attr(\"action\", \"/ex/sboard/modify\");\r\n");
      out.write("			fObject.submit();\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	/* private Integer rno;\r\n");
      out.write("	private Integer bno;\r\n");
      out.write("	private String replytext;\r\n");
      out.write("	private String replyer;\r\n");
      out.write("\r\n");
      out.write("	private Date regdate;\r\n");
      out.write("	private Date updatedate; */\r\n");
      out.write("	\r\n");
      out.write("	function getPageList(page){\r\n");
      out.write("		$.getJSON(\"/ex/replies/\"+bno+\"/\"+page,function(data){\r\n");
      out.write("			console.log(data.list.length);\r\n");
      out.write("			var str=\"\";\r\n");
      out.write("			$(data.list).each(function(){\r\n");
      out.write("				str+=\"<li data-rno='\"+this.rno+\"' class='replyLi'>\"\r\n");
      out.write("				+this.rno+\" \"+this.replyer+\":\"+this.replytext+\" <button>Mod</button></li>\"\r\n");
      out.write("			})\r\n");
      out.write("			$(\"#replies\").html(str);\r\n");
      out.write("			printPaging(data.pageMaker)\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("function printPaging(pageMaker){\r\n");
      out.write("	\r\n");
      out.write("	var str = \"\";\r\n");
      out.write("	\r\n");
      out.write("	if(pageMaker.prev){\r\n");
      out.write("		str += \"<a href='\"+(pageMaker.startPage-1)+\"'> << </a>\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	for(var i=pageMaker.startPage, len = pageMaker.endPage; i <= len; i++){				\r\n");
      out.write("			var strClass= pageMaker.page == i?'class=active':'';\r\n");
      out.write("		  str += \"<a  \"+strClass+\" href='\"+i+\"'>\"+i+\"</a>\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(pageMaker.next){\r\n");
      out.write("		str += \"<a href='\"+(pageMaker.endPage + 1)+\"'> >> </a>\";\r\n");
      out.write("	}\r\n");
      out.write("	$('.pagination').html(str);	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("	<form class=\"form\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("		<input type='hidden' name='bno' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("			type='hidden' name='page' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("			type='hidden' name='perPageNum' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.perPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type='hidden' name='searchType' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type='hidden' name='keyword' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("	<h1>read</h1>\r\n");
      out.write("	<h2>\r\n");
      out.write("		<input type=\"text\" name='title' style=\"width: 100%\"\r\n");
      out.write("			value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("	</h2>\r\n");
      out.write("\r\n");
      out.write("	<h2>\r\n");
      out.write("		Content\r\n");
      out.write("		<textarea style=\"width: 100%\" name=\"content\" rows=\"3\"\r\n");
      out.write("			readonly=\"readonly\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("	</h2>\r\n");
      out.write("\r\n");
      out.write("	<h2>\r\n");
      out.write("		Writer <input type=\"text\" name=\"writer\" style=\"width: 100%\"\r\n");
      out.write("			value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("		<h2>\r\n");
      out.write("\r\n");
      out.write("			<!-- /.box-body -->\r\n");
      out.write("			<div class=\"box-footer\">\r\n");
      out.write("				<button type=\"submit\" class=\"btnModify\">Modify</button>\r\n");
      out.write("				<button type=\"submit\" class=\"btnRemove\">REMOVE</button>\r\n");
      out.write("				<button type=\"submit\" class=\"btnList\">LIST ALL</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id='modDiv' style=\"display: none;\">\r\n");
      out.write("				<div class='modal-title'></div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type='text' id='replytext'>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<button type=\"button\" id=\"replyModBtn\">Modify</button>\r\n");
      out.write("					<button type=\"button\" id=\"replyDelBtn\">DELETE</button>\r\n");
      out.write("					<button type=\"button\" id='closeBtn'>Close</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2>Ajax Test Page</h2>\r\n");
      out.write("			<div>\r\n");
      out.write("				<div>\r\n");
      out.write("					REPLYER <input type='text' name='replyer' id='newReplyWriter'>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					REPLY TEXT <input type='text' name='replytext' id='newReplyText'>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button id=\"replyAddBtn\">ADD REPLY</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<ul id=\"replies\">\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class='pagination'></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <h2>Footer</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
